name: Terraform Destroy

on:
  workflow_dispatch: # Manual trigger
  # Uncomment below if you want to run on specific events
  # push:
  #   branches:
  #     - main
  # pull_request:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8 # Specify your Terraform version here

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Destroy
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform destroy -auto-approve
